# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sale_screen.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1210, 680)
        MainWindow.setMinimumSize(QtCore.QSize(1210, 680))
        MainWindow.setMaximumSize(QtCore.QSize(1210, 680))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(r"imgs\bac.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 1212, 680))
        self.background.setMinimumSize(QtCore.QSize(1212, 680))
        self.background.setMaximumSize(QtCore.QSize(1212, 680))
        self.background.setAutoFillBackground(False)
        self.background.setStyleSheet(" background-image: url(.\imgs\sale.PNG);")
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap(r"imgs\sale.PNG"))
        self.background.setScaledContents(True)
        self.background.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.background.setObjectName("background")
        self.btnYes = QtWidgets.QRadioButton(self.centralwidget)
        self.btnYes.setGeometry(QtCore.QRect(670, 520, 40, 40))
        self.btnYes.setMinimumSize(QtCore.QSize(40, 40))
        self.btnYes.setMaximumSize(QtCore.QSize(40, 40))
        self.btnYes.setStyleSheet("border:0;")
        self.btnYes.setText("")
        self.btnYes.setObjectName("btnYes")
        self.btnNo = QtWidgets.QRadioButton(self.centralwidget)
        self.btnNo.setGeometry(QtCore.QRect(770, 520, 40, 40))
        self.btnNo.setMinimumSize(QtCore.QSize(40, 40))
        self.btnNo.setMaximumSize(QtCore.QSize(40, 40))
        self.btnNo.setStyleSheet("border:0;")
        self.btnNo.setText("")
        self.btnNo.setObjectName("btnNo")
        self.inputId = QtWidgets.QLineEdit(self.centralwidget)
        self.inputId.setGeometry(QtCore.QRect(140, 190, 120, 30))
        self.inputId.setMinimumSize(QtCore.QSize(120, 30))
        self.inputId.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setPointSize(13)
        self.inputId.setFont(font)
        self.inputId.setStyleSheet("border: 0; border-bottom: 2px solid #2CD697;")
        self.inputId.setObjectName("inputId")
        self.inputQuantity = QtWidgets.QLineEdit(self.centralwidget)
        self.inputQuantity.setGeometry(QtCore.QRect(460, 190, 120, 30))
        self.inputQuantity.setMinimumSize(QtCore.QSize(120, 30))
        self.inputQuantity.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setPointSize(13)
        self.inputQuantity.setFont(font)
        self.inputQuantity.setStyleSheet("border: 0; border-bottom: 2px solid #2CD697;")
        self.inputQuantity.setObjectName("inputQuantity")
        self.btnAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdd.setGeometry(QtCore.QRect(660, 180, 160, 45))
        self.btnAdd.setMinimumSize(QtCore.QSize(160, 45))
        self.btnAdd.setMaximumSize(QtCore.QSize(160, 45))
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnAdd.setFont(font)
        self.btnAdd.setStyleSheet("#btnAdd{\n"
"    background-color: #2CD697; border: 0; border-radius:15px; color:white;\n"
"}\n"
"#btnAdd:hover{\n"
"    background-color: #309F76; border: 0; border-radius:15px; color: white;\n"
"}")
        self.btnAdd.setObjectName("btnAdd")
        self.inputClient = QtWidgets.QLineEdit(self.centralwidget)
        self.inputClient.setGeometry(QtCore.QRect(260, 480, 180, 30))
        self.inputClient.setMinimumSize(QtCore.QSize(180, 30))
        self.inputClient.setMaximumSize(QtCore.QSize(180, 30))
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setPointSize(13)
        self.inputClient.setFont(font)
        self.inputClient.setStyleSheet("border: 0; border-bottom: 2px solid #2CD697;")
        self.inputClient.setObjectName("inputClient")
        self.inputDiscount = QtWidgets.QLineEdit(self.centralwidget)
        self.inputDiscount.setGeometry(QtCore.QRect(260, 520, 180, 30))
        self.inputDiscount.setMinimumSize(QtCore.QSize(180, 30))
        self.inputDiscount.setMaximumSize(QtCore.QSize(180, 30))
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setPointSize(13)
        self.inputDiscount.setFont(font)
        self.inputDiscount.setStyleSheet("border: 0; border-bottom: 2px solid #2CD697;")
        self.inputDiscount.setObjectName("inputDiscount")
        self.inputMoneyReceived = QtWidgets.QLineEdit(self.centralwidget)
        self.inputMoneyReceived.setGeometry(QtCore.QRect(660, 480, 180, 30))
        self.inputMoneyReceived.setMinimumSize(QtCore.QSize(180, 30))
        self.inputMoneyReceived.setMaximumSize(QtCore.QSize(180, 30))
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setPointSize(13)
        self.inputMoneyReceived.setFont(font)
        self.inputMoneyReceived.setStyleSheet("border: 0; border-bottom: 2px solid #2CD697;")
        self.inputMoneyReceived.setObjectName("inputMoneyReceived")
        self.labelChange = QtWidgets.QLineEdit(self.centralwidget)
        self.labelChange.setEnabled(False)
        self.labelChange.setGeometry(QtCore.QRect(1010, 480, 120, 25))
        self.labelChange.setMinimumSize(QtCore.QSize(120, 25))
        self.labelChange.setMaximumSize(QtCore.QSize(120, 25))
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setPointSize(13)
        self.labelChange.setFont(font)
        self.labelChange.setStyleSheet("border: 0; border-bottom: 2px solid #2CD697;")
        self.labelChange.setObjectName("labelChange")
        self.labelTotal = QtWidgets.QLineEdit(self.centralwidget)
        self.labelTotal.setEnabled(False)
        self.labelTotal.setGeometry(QtCore.QRect(1010, 520, 120, 25))
        self.labelTotal.setMinimumSize(QtCore.QSize(120, 25))
        self.labelTotal.setMaximumSize(QtCore.QSize(120, 25))
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setPointSize(13)
        self.labelTotal.setFont(font)
        self.labelTotal.setStyleSheet("border: 0; border-bottom: 2px solid #2CD697;")
        self.labelTotal.setObjectName("labelTotal")
        self.labelDiscount = QtWidgets.QLineEdit(self.centralwidget)
        self.labelDiscount.setEnabled(False)
        self.labelDiscount.setGeometry(QtCore.QRect(1010, 550, 120, 25))
        self.labelDiscount.setMinimumSize(QtCore.QSize(120, 25))
        self.labelDiscount.setMaximumSize(QtCore.QSize(120, 25))
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setPointSize(13)
        self.labelDiscount.setFont(font)
        self.labelDiscount.setStyleSheet("border: 0; border-bottom: 2px solid #2CD697;")
        self.labelDiscount.setObjectName("labelDiscount")
        self.labelGrandTotal = QtWidgets.QLineEdit(self.centralwidget)
        self.labelGrandTotal.setEnabled(False)
        self.labelGrandTotal.setGeometry(QtCore.QRect(1010, 590, 120, 25))
        self.labelGrandTotal.setMinimumSize(QtCore.QSize(120, 25))
        self.labelGrandTotal.setMaximumSize(QtCore.QSize(120, 25))
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setPointSize(13)
        self.labelGrandTotal.setFont(font)
        self.labelGrandTotal.setStyleSheet("border: 0; border-bottom: 2px solid #2CD697;")
        self.labelGrandTotal.setObjectName("labelGrandTotal")
        self.btnCheckout = QtWidgets.QPushButton(self.centralwidget)
        self.btnCheckout.setGeometry(QtCore.QRect(110, 580, 160, 45))
        self.btnCheckout.setMinimumSize(QtCore.QSize(160, 45))
        self.btnCheckout.setMaximumSize(QtCore.QSize(160, 45))
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnCheckout.setFont(font)
        self.btnCheckout.setStyleSheet("#btnCheckout{\n"
"    background-color: #2CD697; border: 0; border-radius:15px; color:white;\n"
"}\n"
"#btnCheckout:hover{\n"
"    background-color: #309F76; border: 0; border-radius:15px; color: white;\n"
"}")
        self.btnCheckout.setObjectName("btnCheckout")
        self.btnDelete = QtWidgets.QPushButton(self.centralwidget)
        self.btnDelete.setGeometry(QtCore.QRect(300, 580, 160, 45))
        self.btnDelete.setMinimumSize(QtCore.QSize(160, 45))
        self.btnDelete.setMaximumSize(QtCore.QSize(160, 45))
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnDelete.setFont(font)
        self.btnDelete.setStyleSheet("#btnDelete{\n"
"    background-color: #2CD697; border: 0; border-radius:15px; color:white;\n"
"}\n"
"#btnDelete:hover{\n"
"    background-color: #309F76; border: 0; border-radius:15px; color: white;\n"
"}")
        self.btnDelete.setObjectName("btnDelete")
        self.tableShoppingCart = QtWidgets.QTableWidget(self.centralwidget)
        self.tableShoppingCart.setGeometry(QtCore.QRect(120, 270, 1000, 175))
        self.tableShoppingCart.setMinimumSize(QtCore.QSize(1000, 175))
        self.tableShoppingCart.setMaximumSize(QtCore.QSize(1000, 175))
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setPointSize(12)
        self.tableShoppingCart.setFont(font)
        self.tableShoppingCart.setAutoFillBackground(False)
        self.tableShoppingCart.setStyleSheet("background-color: #D9D9D9; color: #2CD697; border:0;")
        self.tableShoppingCart.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableShoppingCart.setAlternatingRowColors(True)
        self.tableShoppingCart.setShowGrid(True)
        self.tableShoppingCart.setGridStyle(QtCore.Qt.SolidLine)
        self.tableShoppingCart.setRowCount(0)
        self.tableShoppingCart.setColumnCount(5)
        self.tableShoppingCart.setObjectName("tableShoppingCart")
        item = QtWidgets.QTableWidgetItem()
        self.tableShoppingCart.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableShoppingCart.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableShoppingCart.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableShoppingCart.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableShoppingCart.setHorizontalHeaderItem(4, item)
        self.tableShoppingCart.horizontalHeader().setDefaultSectionSize(190)
        self.btnSignOut = QtWidgets.QPushButton(self.centralwidget)
        self.btnSignOut.setGeometry(QtCore.QRect(1060, 20, 100, 45))
        self.btnSignOut.setMinimumSize(QtCore.QSize(100, 45))
        self.btnSignOut.setMaximumSize(QtCore.QSize(100, 45))
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnSignOut.setFont(font)
        self.btnSignOut.setStyleSheet("#btnSignOut{\n"
"    background-color: #2CD697; border: 0; border-radius:15px; color:white;\n"
"}\n"
"#btnSignOut:hover{\n"
"    background-color: #309F76; border: 0; border-radius:15px; color: white;\n"
"}")
        self.btnSignOut.setObjectName("btnSignOut")
        self.btnRegisterEmployee = QtWidgets.QPushButton(self.centralwidget)
        self.btnRegisterEmployee.setGeometry(QtCore.QRect(870, 20, 160, 45))
        self.btnRegisterEmployee.setMinimumSize(QtCore.QSize(160, 45))
        self.btnRegisterEmployee.setMaximumSize(QtCore.QSize(160, 45))
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnRegisterEmployee.setFont(font)
        self.btnRegisterEmployee.setStyleSheet("#btnRegisterEmployee{\n"
"    background-color: #ffffff; border: 0; border-radius:15px; color:#2CD697;\n"
"}\n"
"#btnRegisterEmployee:hover{\n"
"    background-color: #D9D9D9; border: 0; border-radius:15px; color: #2CD697;\n"
"}")
        self.btnRegisterEmployee.setObjectName("btnRegisterEmployee")
        self.btnAddProduct = QtWidgets.QPushButton(self.centralwidget)
        self.btnAddProduct.setGeometry(QtCore.QRect(670, 20, 160, 45))
        self.btnAddProduct.setMinimumSize(QtCore.QSize(160, 45))
        self.btnAddProduct.setMaximumSize(QtCore.QSize(160, 45))
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnAddProduct.setFont(font)
        self.btnAddProduct.setStyleSheet("#btnAddProduct{\n"
"    background-color: #ffffff; border: 0; border-radius:15px; color:#2CD697;\n"
"}\n"
"#btnAddProduct:hover{\n"
"    background-color: #D9D9D9; border: 0; border-radius:15px; color: #2CD697;\n"
"}")
        self.btnAddProduct.setObjectName("btnAddProduct")
        self.btnStock = QtWidgets.QPushButton(self.centralwidget)
        self.btnStock.setGeometry(QtCore.QRect(480, 20, 160, 45))
        self.btnStock.setMinimumSize(QtCore.QSize(160, 45))
        self.btnStock.setMaximumSize(QtCore.QSize(160, 45))
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnStock.setFont(font)
        self.btnStock.setStyleSheet("#btnStock{\n"
"    background-color: #ffffff; border: 0; border-radius:15px; color:#2CD697;\n"
"}\n"
"#btnStock:hover{\n"
"    background-color: #D9D9D9; border: 0; border-radius:15px; color: #2CD697;\n"
"}")
        self.btnStock.setObjectName("btnStock")
        self.btnSale = QtWidgets.QPushButton(self.centralwidget)
        self.btnSale.setGeometry(QtCore.QRect(290, 20, 160, 45))
        self.btnSale.setMinimumSize(QtCore.QSize(160, 45))
        self.btnSale.setMaximumSize(QtCore.QSize(160, 45))
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnSale.setFont(font)
        self.btnSale.setStyleSheet("#btnSale{\n"
"    background-color: #D9D9D9; border: 0; border-radius:15px; color: #2CD697;\n"
"}")
        self.btnSale.setObjectName("btnSale")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(50, 10, 80, 65))
        self.logo.setMinimumSize(QtCore.QSize(80, 65))
        self.logo.setMaximumSize(QtCore.QSize(80, 65))
        self.logo.setAutoFillBackground(False)
        self.logo.setStyleSheet(r"background-image: url(.\imgs\background_component.png);")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(r"imgs\background_component.png"))
        self.logo.setScaledContents(True)
        self.logo.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.logo.setObjectName("logo")
        self.labelName = QtWidgets.QLineEdit(self.centralwidget)
        self.labelName.setEnabled(False)
        self.labelName.setGeometry(QtCore.QRect(130, 20, 157, 30))
        self.labelName.setMinimumSize(QtCore.QSize(157, 30))
        self.labelName.setMaximumSize(QtCore.QSize(157, 30))
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setPointSize(13)
        self.labelName.setFont(font)
        self.labelName.setStyleSheet("border: 0; background-color: #032066; color: #ffffff;")
        self.labelName.setObjectName("labelName")
        self.labelJob = QtWidgets.QLineEdit(self.centralwidget)
        self.labelJob.setEnabled(False)
        self.labelJob.setGeometry(QtCore.QRect(130, 50, 157, 16))
        self.labelJob.setMinimumSize(QtCore.QSize(157, 16))
        self.labelJob.setMaximumSize(QtCore.QSize(157, 16))
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setPointSize(13)
        self.labelJob.setFont(font)
        self.labelJob.setStyleSheet("border: 0; background-color: #032066; color: #ffffff;")
        self.labelJob.setObjectName("labelJob")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Stock Manager"))
        self.btnAdd.setText(_translate("MainWindow", "Add"))
        self.inputDiscount.setPlaceholderText(_translate("MainWindow", "(%)"))
        self.btnCheckout.setText(_translate("MainWindow", "Checkout"))
        self.btnDelete.setText(_translate("MainWindow", "Delete"))
        item = self.tableShoppingCart.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.tableShoppingCart.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Product"))
        item = self.tableShoppingCart.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Quantity"))
        item = self.tableShoppingCart.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Unit price"))
        item = self.tableShoppingCart.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Subtotal"))
        self.btnSignOut.setText(_translate("MainWindow", "Sign out"))
        self.btnRegisterEmployee.setText(_translate("MainWindow", "Register employee"))
        self.btnAddProduct.setText(_translate("MainWindow", "Add product"))
        self.btnStock.setText(_translate("MainWindow", "Stock"))
        self.btnSale.setText(_translate("MainWindow", "Sale"))

